Increase gnome-panel loaded check to 15 seconds.

diff --git a/sch-scripts/gnome-panel b/sch-scripts/gnome-panel
--- a/sch-scripts/gnome-panel
+++ b/sch-scripts/gnome-panel
@@ -1,12 +1,19 @@
 #!/bin/sh
+# Restart gnome-panel if it fails to load (LP: #1078679).
 
-if [ "$LTSP_FATCLIENT" != "True" ]; then
-    exec /usr/bin/gnome-panel "$@"
+prog=${0##*/}
+if [ ! -x "/usr/bin/$prog" ]; then
+    echo "$prog: command not found" >&2
+    exit 127
 fi
 
-/usr/bin/gnome-panel "$@" &
-sleep 10
+if [ "$LTSP_FATCLIENT" != "True" ]; then
+    exec "/usr/bin/$prog" "$@"
+fi
+
+"/usr/bin/$prog" "$@" &
+sleep 15
 if ! pgrep -nx indicator-sound -U $USER >/dev/null 2>&1; then
-    echo "$(date) - restarting gnome-panel" >> $HOME/.xsession-errors
-    exec /usr/bin/gnome-panel --replace
+    echo "$(date) - restarting $prog" >> $HOME/.xsession-errors
+    exec "/usr/bin/$prog" --replace
 fi
