[ltsp-manager] Bulk renaming of sch-scripts to ltsp-manager.
Commands performed:
cp -a sch-scripts ltsp-manager &&
cd ltsp-manager &&
for f in $(grep -rl sch-scripts . | sed "/\.git/d"); do sed "s/sch-scripts/ltsp-manager/g" -i "$f"; done &&
for f in $(find . -depth -iname "*sch-scripts*"); do git mv "$f" "$(echo "$f" | rev | sed "s/stpircs-hcs/reganam-pstl/" | rev)"; done &&
git remote set-url origin git+ssh://git.launchpad.net/~ltsp-upstream/ltsp/+git/ltsp-manager

diff --git a/sbin/ltsp-manager b/sbin/ltsp-manager
--- a/sbin/ltsp-manager
+++ b/sbin/ltsp-manager
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Wrapper to execute sch-scripts as root.
+# Wrapper to execute ltsp-manager as root.
 # Copyright (C) 2012-2013 Alkis Georgopoulos <alkisg@gmail.com>
 # License GNU GPL version 3 or newer <http://gnu.org/licenses/gpl.html>
 
@@ -23,28 +23,28 @@ exec_input() {
     done
 }
 
-if [ ! -x /usr/share/sch-scripts/sch-scripts.py ]; then
-    echo "/usr/share/sch-scripts/sch-scripts.py not found" >&2
+if [ ! -x /usr/share/ltsp-manager/ltsp-manager.py ]; then
+    echo "/usr/share/ltsp-manager/ltsp-manager.py not found" >&2
     exit 1
 fi
 
-cd /usr/share/sch-scripts
+cd /usr/share/ltsp-manager
 case "$1" in
     # help and version need to run without root
     -h|--help|-v|--version)
-        exec ./sch-scripts.py "$@"
+        exec ./ltsp-manager.py "$@"
         ;;
     *)
         if [ "$(id -u)" -ne 0 ]; then
-            pkexec /usr/sbin/sch-scripts "$@" | exec_input
+            pkexec /usr/sbin/ltsp-manager "$@" | exec_input
 # The above unfortunately wastes one extra shell.
 # mkfifo works but it makes the code a bit complicated.
-# This doesn't work, it waits until sch-scripts is closed to evaluate its output
+# This doesn't work, it waits until ltsp-manager is closed to evaluate its output
 #            exec_input <<EOF
-#$(pkexec /usr/sbin/sch-scripts "$@")
+#$(pkexec /usr/sbin/ltsp-manager "$@")
 #EOF
         else
-            # sch-scripts rely on some SUDO* variables, set them if unset
+            # ltsp-manager rely on some SUDO* variables, set them if unset
             if [ -n "$PKEXEC_UID" ] && [ -z "$SUDO_USER" ]; then
                 IFS=":" read SUDO_USER dummy SUDO_UID SUDO_GID dummy <<EOF
 $(getent passwd "$PKEXEC_UID")
@@ -52,10 +52,10 @@ EOF
                 export SUDO_USER SUDO_UID SUDO_GID
             fi
             if [ -n "$PKEXEC_UID" ]; then
-                exec ./sch-scripts.py "$@"
+                exec ./ltsp-manager.py "$@"
             else
-                # This means that the user ran sudo sch-scripts without pkexec
-                ./sch-scripts.py "$@" | exec_input
+                # This means that the user ran sudo ltsp-manager without pkexec
+                ./ltsp-manager.py "$@" | exec_input
             fi
         fi
         ;;
diff --git a/sbin/shared-folders b/sbin/shared-folders
--- a/sbin/shared-folders
+++ b/sbin/shared-folders
@@ -2,9 +2,9 @@
 # Copyright (C) 2012 Alkis Georgopoulos <alkisg@gmail.com>
 # License GNU GPL version 3 or newer <http://gnu.org/licenses/gpl.html>
 
-if [ ! -x /usr/share/sch-scripts/shared_folders.py ]; then
-    echo "/usr/share/sch-scripts/shared_folders.py not found!" >&2
+if [ ! -x /usr/share/ltsp-manager/shared_folders.py ]; then
+    echo "/usr/share/ltsp-manager/shared_folders.py not found!" >&2
     exit 1
 fi
-cd /usr/share/sch-scripts
+cd /usr/share/ltsp-manager
 exec ./shared_folders.py "$@"
