Revert r164 until it's more widely tested.

diff --git a/share/sch-scripts/gnome-panel b/share/sch-scripts/gnome-panel
--- a/share/sch-scripts/gnome-panel
+++ b/share/sch-scripts/gnome-panel
@@ -12,3 +12,8 @@ if [ "$LTSP_FATCLIENT" != "True" ]; then
 fi
 
 "/usr/bin/$prog" "$@" &
+sleep 15
+if ! pgrep -nx indicator-sound -U $USER >/dev/null 2>&1; then
+    echo "$(date) - restarting $prog" >> $HOME/.xsession-errors
+    exec "/usr/bin/$prog" --replace
+fi
